# -*- coding: utf-8 -*-
"""estrutura_de_dados_camila

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uyoqk9lhp-AWgaqYkuuIbeLH_Wb_ijxZ
"""

# -----------------------------------------
# Script: fila_menu.py
# -----------------------------------------
# Este programa implementa uma fila com operações básicas:
# enfileirar, desenfileirar, consultar e contar.
# O usuário interage através de um menu no console.
# -----------------------------------------

# Criando a fila (lista vazia)
fila = []


# Função para inserir elemento no final da fila
def enfileirar():
    elemento = input("Digite o elemento a ser enfileirado: ")
    fila.append(elemento)
    print(f"✅ '{elemento}' foi adicionado à fila.")


# Função para remover elemento do início da fila
def desenfileirar():
    if len(fila) == 0:
        print("⚠️ A fila está vazia. Nenhum elemento para remover.")
    else:
        elemento = fila.pop(0)
        print(f"🚪 '{elemento}' foi removido da fila.")


# Função para consultar o primeiro elemento da fila (sem remover)
def consultar():
    if len(fila) == 0:
        print("⚠️ A fila está vazia.")
    else:
        print(f"👀 O primeiro elemento da fila é: '{fila[0]}'.")


# Função para contar o número de elementos na fila
def contar():
    print(f"📊 A fila contém {len(fila)} elemento(s).")


# Função principal - menu de operações
def menu():
    while True:
        print("\n=== MENU DA FILA ===")
        print("1 - Enfileirar elemento")
        print("2 - Desenfileirar elemento")
        print("3 - Consultar primeiro elemento")
        print("4 - Contar elementos")
        print("5 - Exibir fila completa")
        print("0 - Sair")

        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            enfileirar()
        elif opcao == "2":
            desenfileirar()
        elif opcao == "3":
            consultar()
        elif opcao == "4":
            contar()
        elif opcao == "5":
            print(f"📜 Fila atual: {fila}")
        elif opcao == "0":
            print("👋 Encerrando o programa. Até logo!")
            break
        else:
            print("❌ Opção inválida. Tente novamente.")


# Execução do programa
if __name__ == "__main__":
    menu()